// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/callback": {
            "get": {
                "description": "Validates the CSRF state, exchanges the authorization code, provisions the user on first login (JIT), sets the nv_session cookie, and redirects to the post-login URL.",
                "tags": [
                    "auth"
                ],
                "summary": "OIDC callback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "CSRF state issued by /auth/login",
                        "name": "state",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "OIDC authorization code",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Found"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/auth/login": {
            "get": {
                "description": "Sets a CSRF state cookie and redirects to the OIDC provider's authorization endpoint (authorization-code flow).",
                "tags": [
                    "auth"
                ],
                "summary": "Start OIDC login",
                "responses": {
                    "302": {
                        "description": "Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Clears the nv_session cookie.",
                "tags": [
                    "auth"
                ],
                "summary": "Log out",
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "description": "Returns the id and email of the authenticated caller.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Current user",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            }
        },
        "/auth/token": {
            "post": {
                "description": "Authenticates against the OIDC provider's token endpoint via the password grant and issues the nv_session cookie.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Native email/password login",
                "parameters": [
                    {
                        "description": "Credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.tokenRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/conversations": {
            "get": {
                "description": "Returns the workspace's conversations, most recently active first.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversations"
                ],
                "summary": "List a workspace's conversations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace UUID",
                        "name": "workspace_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "description": "Creates an untitled conversation from a JSON body {\"workspace_id\": uuid}.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversations"
                ],
                "summary": "Create a conversation",
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/conversations/{id}/messages": {
            "get": {
                "description": "Returns the conversation's messages, oldest first.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversations"
                ],
                "summary": "List a conversation's messages",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Conversation UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Probes every infrastructure dependency (Postgres, Qdrant, MinIO, Keycloak, Ollama) and reports each one. Returns 200 when all are healthy and 503 when any is down.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Get all health status",
                "responses": {
                    "200": {
                        "description": "All dependencies healthy",
                        "schema": {
                            "$ref": "#/definitions/health.Report"
                        }
                    },
                    "503": {
                        "description": "One or more dependencies are down",
                        "schema": {
                            "$ref": "#/definitions/health.Report"
                        }
                    }
                }
            }
        },
        "/query": {
            "post": {
                "description": "Embeds the question from a JSON body {\"workspace_id\": uuid, \"question\": string, \"top_k\": int, \"conversation_id\": uuid (optional)} and returns the top-k matching chunks ordered by descending similarity score. If conversation_id is set, persists the question as a message on that conversation (no answer is generated here to persist).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "query"
                ],
                "summary": "Query a workspace",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/query/stream": {
            "post": {
                "description": "Runs retrieval for a JSON body {\"workspace_id\": uuid, \"question\": string, \"top_k\": int, \"conversation_id\": uuid (optional)}, then streams SSE events: one \"sources\" event with the grounding chunks, incremental \"token\" events, and a terminal \"done\" or \"error\" event. If conversation_id is set, persists the question and the completed answer (with sources) as messages on that conversation.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "query"
                ],
                "summary": "Stream a grounded answer (SSE)",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/sources": {
            "get": {
                "description": "Returns the sources of a workspace the caller belongs to.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sources"
                ],
                "summary": "List sources",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace UUID",
                        "name": "workspace_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "description": "Uploads one or more files to object storage and starts background indexing. Returns the created source and its status_url.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sources"
                ],
                "summary": "Create a source",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace UUID",
                        "name": "workspace_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Source name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Files to ingest (repeatable)",
                        "name": "files",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/sources/{id}": {
            "delete": {
                "description": "Deletes the source, its chunks and file records, its Qdrant vectors, and its object-storage files.",
                "tags": [
                    "sources"
                ],
                "summary": "Delete a source",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Source UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/sources/{id}/chunks": {
            "get": {
                "description": "Returns the indexed chunks produced from a source.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sources"
                ],
                "summary": "List chunks of a source",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Source UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/sources/{id}/files": {
            "get": {
                "description": "Returns the original files stored for a source, with size and content type.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sources"
                ],
                "summary": "List files of a source",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Source UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/sources/{id}/files/content": {
            "get": {
                "description": "Streams the raw content of a single file (by its path relative to the source root) for inline preview or download.",
                "tags": [
                    "sources"
                ],
                "summary": "Stream a source file's content",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Source UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "File path relative to the source root",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/sources/{id}/ingest": {
            "post": {
                "description": "Re-downloads the source's files from object storage and re-indexes them in the background.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sources"
                ],
                "summary": "Re-ingest a source",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Source UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "409": {
                        "description": "Conflict"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/sources/{id}/status": {
            "get": {
                "description": "Server-Sent Events stream of indexing progress: progress events, then a terminal done or error event. Heartbeat every 30s; 15min timeout.",
                "tags": [
                    "sources"
                ],
                "summary": "Stream indexing status (SSE)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Source UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/workspaces": {
            "get": {
                "description": "Returns the workspaces the authenticated caller belongs to.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workspaces"
                ],
                "summary": "List workspaces",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "description": "Creates a workspace from a JSON body {\"name\": string}; the caller becomes its owner.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workspaces"
                ],
                "summary": "Create a workspace",
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/workspaces/{workspace_id}/model-settings": {
            "get": {
                "description": "Returns the workspace's chosen completion and embedding models. Empty fields mean it uses the server default (Ollama).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "modelconfig"
                ],
                "summary": "Get a workspace's model settings",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/modelconfig.settingsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/workspaces/{workspace_id}/model-settings/embedding": {
            "put": {
                "description": "Sets the embedding provider and model. The provider is probed for its vector dimension and a matching Qdrant collection is created. Existing sources were embedded with the previous model and are NOT migrated: the response reports how many need re-indexing, and until they are, retrieval finds nothing.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "modelconfig"
                ],
                "summary": "Set the workspace's embedding model",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/modelconfig.EmbeddingChange"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    },
                    "502": {
                        "description": "Bad Gateway"
                    }
                }
            }
        },
        "/workspaces/{workspace_id}/model-settings/llm": {
            "put": {
                "description": "Sets the default provider and model used to answer queries. Changing it affects only the next query — nothing is re-indexed.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "modelconfig"
                ],
                "summary": "Set the workspace's completion model",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/workspaces/{workspace_id}/providers": {
            "get": {
                "description": "Returns the provider catalog annotated with which providers this workspace has an API key for. The key itself is never returned, only a 4-character hint.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "modelconfig"
                ],
                "summary": "List model providers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/modelconfig.ProviderStatus"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/workspaces/{workspace_id}/providers/{provider}/credential": {
            "put": {
                "description": "Stores an API key for a provider (BYOK), encrypted at rest. The key is validated against the provider before being saved, so an invalid key is rejected here rather than failing later mid-answer.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "modelconfig"
                ],
                "summary": "Save a provider API key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Provider ID",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    },
                    "502": {
                        "description": "Bad Gateway"
                    }
                }
            },
            "delete": {
                "description": "Removes the workspace's stored API key for a provider.",
                "tags": [
                    "modelconfig"
                ],
                "summary": "Delete a provider API key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Provider ID",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/workspaces/{workspace_id}/providers/{provider}/models": {
            "get": {
                "description": "Lists the models the workspace's API key can reach, fetched live from the provider rather than from a hardcoded list. If purpose is set and the provider can self-report per-model capability, the list is filtered to models usable for that purpose (e.g. excluding chat-only models from an embedding picker); otherwise purpose is ignored and the full list is returned.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "modelconfig"
                ],
                "summary": "List a provider's models",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Provider ID",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "completion",
                            "embedding"
                        ],
                        "type": "string",
                        "description": "Filter to models usable for this purpose",
                        "name": "purpose",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.ModelInfo"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    },
                    "502": {
                        "description": "Bad Gateway"
                    }
                }
            }
        },
        "/workspaces/{workspace_id}/reindex": {
            "post": {
                "description": "Queues re-ingestion of all the workspace's sources, re-embedding them with the current embedding model. Required after changing the embedding model, since a source's existing vectors belong to the previous model's collection. Returns immediately; progress streams per source over /sources/{id}/status.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "modelconfig"
                ],
                "summary": "Re-index every source in the workspace",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/modelconfig.reindexResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.tokenRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "catalog.Provider": {
            "type": "string",
            "enum": [
                "ollama",
                "anthropic",
                "gemini",
                "openrouter",
                "groq",
                "github",
                "openai"
            ],
            "x-enum-varnames": [
                "Ollama",
                "Anthropic",
                "Gemini",
                "OpenRouter",
                "Groq",
                "GitHub",
                "OpenAI"
            ]
        },
        "health.Report": {
            "type": "object",
            "properties": {
                "services": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "modelconfig.EmbeddingChange": {
            "type": "object",
            "properties": {
                "collection": {
                    "description": "Collection is the Qdrant collection the workspace's vectors now live in.",
                    "type": "string"
                },
                "dimensions": {
                    "description": "Dimensions is the vector size discovered by probing the provider.",
                    "type": "integer"
                },
                "reindex_required": {
                    "description": "ReindexRequired is true when the workspace has sources that were embedded\nwith a different model. Until they are re-indexed, the new collection is\nempty and retrieval finds nothing.",
                    "type": "boolean"
                },
                "stale_sources": {
                    "description": "StaleSources is how many sources need re-indexing.",
                    "type": "integer"
                }
            }
        },
        "modelconfig.ProviderStatus": {
            "type": "object",
            "properties": {
                "api_key_hint": {
                    "description": "APIKeyHint is the last few characters of the stored key, for display. The\nkey itself is never returned.",
                    "type": "string"
                },
                "base_url": {
                    "description": "BaseURL is the endpoint in effect: the workspace's override if it set one,\notherwise the catalog default.",
                    "type": "string"
                },
                "configured": {
                    "description": "Configured reports whether the workspace has a usable credential. Always\ntrue for providers that need no key.",
                    "type": "boolean"
                },
                "free_tier": {
                    "description": "FreeTier flags providers with a usable no-cost tier, which is what makes\nthem viable for local development without running Ollama.",
                    "type": "boolean"
                },
                "name": {
                    "description": "Name is the human-readable label shown in the UI.",
                    "type": "string"
                },
                "provider": {
                    "$ref": "#/definitions/catalog.Provider"
                },
                "requires_api_key": {
                    "description": "RequiresAPIKey is false only for Ollama, which is unauthenticated and\nserver-local.",
                    "type": "boolean"
                },
                "supports_completions": {
                    "description": "SupportsCompletions and SupportsEmbeddings gate which dropdowns a\nprovider may appear in. Anthropic has no embeddings API at all, and\nGroq/OpenRouter/GitHub Models serve chat models only — offering them as\nan embedding backend would produce a runtime failure at index time.",
                    "type": "boolean"
                },
                "supports_embeddings": {
                    "type": "boolean"
                }
            }
        },
        "modelconfig.reindexResponse": {
            "type": "object",
            "properties": {
                "queued": {
                    "type": "integer"
                }
            }
        },
        "modelconfig.settingsResponse": {
            "type": "object",
            "properties": {
                "embedding_dimensions": {
                    "type": "integer"
                },
                "embedding_model": {
                    "type": "string"
                },
                "embedding_provider": {
                    "$ref": "#/definitions/catalog.Provider"
                },
                "llm_model": {
                    "type": "string"
                },
                "llm_provider": {
                    "$ref": "#/definitions/catalog.Provider"
                }
            }
        },
        "types.ModelInfo": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "ID is the value to send as CompletionRequest.Model.",
                    "type": "string"
                },
                "name": {
                    "description": "Name is a human-readable label. Providers that expose no display name\nrepeat the ID here.",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "NeuralVault API",
	Description:      "API for NeuralVault",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
