ignore:
  - "api/cmd/**"
  - "api/docs/**"
  - "api/internal/storage/storage.go"
  - "api/internal/vectorstorage/vectorstorage.go"
  - "api/internal/objectstorage/objectstorage.go"
  - "api/internal/router/router.go"
  - "api/internal/sources/routes.go"
